### ISSUE TITLE
[DISCUSS] Move allure-android into allure-kotlin

### ISSUE THREAD

**Issue by viclovsky** [allure-framework/allure-kotlin#16]
It is preferable to have one repository with allure-kotlin and allure-android.

All steps, which are presented bellow should be discuss (It is not final plan)

In allure-kotlin
* Move allure-android into allure-kotlin as new modules
* Release new version allure-kotlin 

In allure-android
* Create a migration guide
* Archive allure-android

**Comment by kamildziadek** [comment]
I really like the idea behind having this in a single repository:
- Android instrumentation test is just another testing framework that is to be supported;
- adding the support for another framework on Android will be done much faster (like [cucumber android](https://github.com/cucumber/cucumber-android));
- more code can be shared this way;
- any changes/refactoring in the commons module will be quickly caught in compile-time by other modules.
- **allure-android** will be updated quicker in case of any bugfixes on the side of common modules.

On top of that, the **allure-android** repository will be completely changed, and its modules should be removed:
- **allure-android-model** will be replaced by the **allure-kotlin-model**;
- **allure-android-commons** will be replaced by the **allure-kotlin-commons**;
- **allure-android-espresso** should be renamed to just **allure-android-junit4**, as it doesn't support only Espresso, but JUnit4 instrumentation tests in general.

Furthermore, the implementation of allure-android in my [initial draft](https://github.com/kamildziadek/allure-kotlin/tree/master/allure-kotlin-android) is super easy to integrate with this repository **allure-kotlin**. It will require a small effort from my side, as the whole setup is already in place.

Regarding the plan for **allure-kotlin**:
- We don't really have to move **allure-android** in here. The **allure-android** implementation that I have [in-place](https://github.com/kamildziadek/allure-kotlin/tree/master/allure-kotlin-android) completely invalidates **allure-android**. The structure is different (only a single module), libraries are refreshed, it's more robust (support for both instrumentation and robolectric tests), and is integrated with **allure-kotlin** already.
- I also have a **sample** project that shows how the new **allure-android** can be used. I think it's worth adding in here, before the release.

In terms of a plan for **allure-android** it looks good to me. The migration guide is necessary and it shouldn't be hard to prepare. We could even add a sample with step by step migration in the form of commits. At the very end, I also thought about writing a Medium article to let the people know, why, and how was this done.

What do you guys think about that?

**Comment by viclovsky** [comment]
Here “Move allure-android into allure-kotlin as new modules” I meant we need to implement new version allure-android which will use allure-kotlin and will save old features (for example Multidex support). It will not be a problem if we have two implementation for android while allure-kotlin is under testing.

**Comment by kamildziadek** [comment]
>Here “Move allure-android into allure-kotlin as new modules” I meant we need to implement new version allure-android which will use allure-kotlin and will save old features (for example Multidex support). It will not be a problem if we have two implementation for android while allure-kotlin is under testing.

Yeah, of course. The API will be greatly extended, but I doubt anything will be cut down. I will go through the whole repo to find out different features that may be missing.
