### ISSUE TITLE
Create a migration guide from allure-android

### ISSUE THREAD

**Issue by viclovsky** [allure-framework/allure-kotlin#28]

**Comment by kamildziadek** [comment]
Pull request have been made to `allure-android` repository: https://github.com/allure-framework/allure-android/pull/54. @viclovsky please check it

**Comment by kamildziadek** [comment]
@viclovsky update to the PR has been made. I don't have permissions to `allure-android` so please merge the migration guide there, if you think it's satisfying enough :)

**Comment by viclovsky** [comment]
Hello, @kamildziadek  
I also don't have permission to allure-android, but Artem(@eroshenkoam ) has. I'll ask him to merge the PR.
