### ISSUE TITLE
Failed to resolve allure-kotlin-android dependency(2.1.1)

### ISSUE THREAD

**Issue by RuslanSelenium** [allure-framework/allure-kotlin#31]
Hello

I add those 4 lines in my .gradle file:
![image](https://user-images.githubusercontent.com/4572776/92901307-70b97a80-f431-11ea-8a8a-952bc99c9321.png)

I press Sync, and got an error:
![image](https://user-images.githubusercontent.com/4572776/92901527-9ba3ce80-f431-11ea-8c8e-8dbea28eb62f.png)

Allure Kotlin dependencies was resolved successfully, but allure-kotlin-android has been failed :(

Could you pls fix or provide me configuration example?

TY in advance.

**Comment by kamildziadek** [comment]
@viclovsky there is still a problem with publishing the Android artifact. It seems that the `pom` file is not uploaded to bintray which could be a cause of failing to resolve dependency. Could u please take a look at it?

**Comment by kamildziadek** [comment]
Thanks @viclovsky. Version 2.1.2 deployed with the fix.
