### ISSUE TITLE
how to scan all the cases in the AndroidTest apk

### ISSUE THREAD

**Issue by wakelay** [allure-framework/allure-kotlin#35]

**Comment by wakelay** [comment]
I wonder if the AllureAndroidJUnitRunner can do this ..Thanks

**Comment by viclovsky** [comment]
Hi, @wakelay . Could you explain what does "scan all the cases" mean? What issue or problem are you solving?

**Comment by wakelay** [comment]
> Hi, @wakelay . Could you explain what does "scan all the cases" mean? What issue or problem are you solving?

Hi @viclovsky ，I just want to know how many classes and cases  in the AndroidTest.apk,  I want to execute cases concurrently;

**Comment by Badya** [comment]
> > Hi, @wakelay . Could you explain what does "scan all the cases" mean? What issue or problem are you solving?
> 
> Hi @viclovsky ，I just want to know how many classes and cases in the AndroidTest.apk, I want to execute cases concurrently;

Hi, @wakelay, it doesn't seem to be allure related, since allure doesn't respond for launching and running tests. You can take a look at https://github.com/shazam/fork which I used to exec test cases on several devices in parallel.
