### ISSUE TITLE
Migration from bintray to mavenCentral

### ISSUE THREAD

**Issue by Malinskiy** [allure-framework/allure-kotlin#49]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
allure-kotlin is available via `https://dl.bintray.com/qameta/maven`

#### What is the expected behavior?
Due to recent announcement of [jCenter + bintray deprecation](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) please move the artifacts to mavenCentral

#### What is the motivation / use case for changing the behavior?
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

#### Other information 
If you need any help with this - please reach out

**Comment by misa** [comment]
When can we expect this migration?

**Comment by baev** [comment]
by the end of March

**Comment by ifeomaro** [comment]
Hello. When should we expect the migration to mavenCentral?

**Comment by kevinzetterstrom** [comment]
Hello, Bintray is again down to warn users of impending shutdown. When will these dependencies be migrated? https://status.bintray.com/

**Comment by Malinskiy** [comment]
Thanks a lot!
https://search.maven.org/search?q=allure-kotlin
